services:
  builder:
    build: .
    image: jme06/openpose:0.2.0
    tty: true
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
              - gpu
    working_dir: /usr/lib/openpose/build/examples/tutorial_api_python
    # command: /bin/bash
    command: python3 01_body_from_image.py
# services:
#   nvidia-test:
#     image: nvidia/cuda:11.5.2-base-ubuntu20.04
#     command: nvidia-smi
#     deploy:
#       resources:
#         reservations:
#           devices:
#             - driver: nvidia
#               count: 1
#               capabilities: [gpu]